name: Create envfile

on: [ push ]

jobs:

  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
#          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456abcdef"
          envkey_SECRET_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
#          some_other_variable: foobar
#          directory: <directory_name>
          file_name: .env
          fail_on_empty: false